### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by antosha417** [AlexSinkin/SinkinAV#1]
https://github.com/AlexSinkin/SinkinAV/blob/e202c3804f5e8dd38867a507fdbb5d69487b773c/Snowflake_%D1%80%D0%B5%D0%BA%D1%83%D1%80%D1%81%D0%B8%D1%8F.py#L3-L38

Поправь код так, чтоб пайчарм ничего не подчёркивал.
Относится и к остальным файлам.

**Comment by AlexSinkin** [comment]
Исправлено

**Comment by antosha417** [comment]
хорошо бы говорить в каких коммитах ты это сделал.

**Comment by antosha417** [comment]
прочитай "правила игры" на нашем сайте и создай issue на каждую задачу
