### ISSUE TITLE
Давай сделаем паузу поменьше

### ISSUE THREAD

**Issue by antosha417** [AlexSinkin/SinkinAV#3]
https://github.com/AlexSinkin/SinkinAV/blob/e202c3804f5e8dd38867a507fdbb5d69487b773c/Landskape''.py#L119

Попробуй сделать плавное движение

**Comment by AlexSinkin** [comment]
Сделал

**Comment by antosha417** [comment]
хорошо бы говорить в каких коммитах ты это сделал.
